name: SAS UI E2E tests

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  e2e_test:
    name: "SAS E2E Tests 🧪"
    runs-on: [ self-hosted, hmpps-github-actions-runner ]
    strategy:
      fail-fast: false
      # Add to the matrix to start splitting the tests across multiple shards
      matrix:
        shard: [1]
    env:
      TZ: Europe/London

      # URLs
      AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk
      DELIUS_URL: https://ndelius.test.probation.service.justice.gov.uk
      OASYS_URL: https://t2.oasys.service.justice.gov.uk/eor/f?p=100:101
      PRISON_API: https://prison-api-dev.prison.service.justice.gov.uk

      # Credentials
      DELIUS_USERNAME: ${{ secrets.E2E_DELIUS_USERNAME }}
      DELIUS_PASSWORD: ${{ secrets.E2E_DELIUS_PASSWORD }}
      OASYS_USERNAME_BOOKING: ${{ secrets.E2E_OASYS_USERNAME_BOOKING }}
      OASYS_PASSWORD_BOOKING: ${{ secrets.E2E_OASYS_PASSWORD_BOOKING }}
      DPS_USERNAME: ${{ secrets.E2E_DPS_USERNAME }}
      HMPPS_AUTH_CLIENT_ID: ${{ secrets.E2E_HMPPS_AUTH_CLIENT_ID }}
      HMPPS_AUTH_CLIENT_SECRET: ${{ secrets.E2E_HMPPS_AUTH_CLIENT_SECRET }}

    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          # Repository is specified so this workflow can be run from another repository
          repository: 'ministryofjustice/hmpps-single-accommodation-service-ui'
          persist-credentials: 'false'

      - name: Setup Node.js environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: '.node-version'
          cache: 'npm'

#      - name: SLSA
#        uses: ministryofjustice/devsecops-actions/sca/slsa@4cd163be7859cd130800d6719d925318826038ea

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Install Playwright
        run: npx playwright install chromium

      - name: Setup data
        run: npm run test:e2e:data:setup

      - name: Parse setup output to environment
        id: setup-data
        run: |
          outputFile=tmp/TEST_ENV.txt
          [ -f $outputFile ] && cat "$outputFile" >> "$GITHUB_ENV" || true

      - name: Run E2E Tests
        env:
          E2E_BASE_URL: 'https://single-accommodation-service-dev.hmpps.service.justice.gov.uk'
          SAS_E2E_PROBATION_USER_USERNAME: ${{ secrets.E2E_SAS_E2E_PROBATION_USER_USERNAME }}
          SAS_E2E_PROBATION_USER_PASSWORD: ${{ secrets.E2E_SAS_E2E_PROBATION_USER_PASSWORD }}
          SAS_E2E_BASE_CASE_NAME: ${{ env.BASE_CASE_NAME }}
        run: npm run test:e2e -- --shard=${{ matrix.shard }}/${{ strategy.job-total }}

      - name: Teardown data
        if: always()
        run: npm run test:e2e:data:teardown

      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: SAS-E2E-playwright-report-${{ matrix.shard }}-of-${{ strategy.job-total }}
          path: test_results/e2e/report
          retention-days: 30
          if-no-files-found: ignore

      - name: Upload E2E artefacts
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: SAS-E2E-artefacts-${{ matrix.shard }}-of-${{ strategy.job-total }}
          path: test_results/e2e/artefacts
          retention-days: 30
          if-no-files-found: ignore

  e2e_test_notify_slack:
    name: "E2E test failure notification"
    needs: e2e_test
    if: ${{ always() && needs.e2e_test.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: ministryofjustice/hmpps-approved-premises-ui/.github/actions/slack_failure_notification@d03ccce7b908369b59e77cb4ce13468dbe6e278a # v1
        with:
          title: "SAS E2E Tests"
          job: "e2e_test"
          channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID }}
          slack_bot_token: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
